apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: app
data:
  POSTGRES_USER: app
  POSTGRES_DB: contactsdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  PORT: ":8082"