apiVersion: v1
kind: Pod
metadata:
  name: contactsapp
  namespace: app
  labels:
    app: contactsapp
spec:
  containers:
  - name: contactsapp
    image: jpalaparthi/contactsrestapi:v01
    env:
     - name: PORT
       valueFrom: 
        configMapKeyRef:
          name: app-config
          key: PORT
     - name: DB_CONNECTION
       valueFrom: 
        secretKeyRef:
          name: app-secret
          key: db-connection
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8082
# "host=db-service user=app password=app123 dbname=contactsdb port=5432 sslmode=disable TimeZone=Asia/Shanghai"
---
kind: Service
apiVersion: v1
metadata:
  name:  contactsapp
  namespace: app
spec:
  selector:
    app: contactsapp
  type:  LoadBalancer
  ports:
  - name:  web
    port:  8082
    targetPort:  8082