apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command: ["sh","-c","for i in $(seq 1 10);do echo 'Hello, job is running';sleep 5;done"] 
          restartPolicy: OnFailure
